/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package romanNumeralCalculatorKata

import kotlin.test.Test
import kotlin.test.assertEquals

class RomanNumeralCalculatorTest {
    private val calculator = RomanNumeralCalculator()
    lateinit var total: String

    @Test fun `one add one equals two`() {
        total = calculator.add("I", "I")
        assertEquals("II", total)
    }

    @Test fun `one add two equals three`() {
        total = calculator.add("I", "II")
        assertEquals("III", total)
    }

    @Test fun `two plus three equals five`() {
        total = calculator.add("II", "III")
        assertEquals("V", total)
    }

    @Test fun `five plus one equals six`() {
        total = calculator.add("V", "I")
        assertEquals("VI", total)
    }

    @Test fun `five plus five equals ten`() {
        total = calculator.add("V", "V")
        assertEquals("X", total)
    }
}
