/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package romanNumeralCalculatorKata

class RomanNumeralCalculator {

    fun add(romanNumeralOne: String, romanNumeralTwo: String): String {
        val total = "$romanNumeralOne$romanNumeralTwo"

        if(total == "IIIII") return "V"
        if(total == "VV") return "X"
        return total
    }
}
