/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package romanNumeralCalculatorKata

class RomanNumeralCalculator {

    private val toRoman = mapOf(
        "IIIII" to "V",
        "VV" to "X"
    )

    fun add(romanNumeralOne: String, romanNumeralTwo: String): String {
        val total = "$romanNumeralOne$romanNumeralTwo"
        return toRoman[total] ?: total
    }
}
